### ISSUE TITLE
Example request

### ISSUE THREAD

**Issue by yakir12** [piever/TableWidgets.jl#1]
This is in reference to the [Discourse topic about personal financing](https://discourse.julialang.org/t/personal-finance-package/12597/8?u=yakir12). It would be very useful (for me...) to have an example where `TableWidgets` helps manually choosing from a limited number of predefined possibilities.

## Pick a category for each bank comment
The table will have two columns, one column for the comments, and one for the categories. The possible values a category can have are finite and come from a list of predefined categories. The initial value of each row in the category column can be `missing` or an `Uncategorized` category (whichever). For instance:
```
+---------------------------------------+------------------------+
|Comment                                |Category                |
+=======================================+========================+
|2018-06-10 ICA SUPERMARKET SODER, MALMO|Expense:Food:Groceires  |
+---------------------------------------+------------------------+
|2018-06-05 SKANETRAFIKEN, MALMO C      |Expense:Transport:Public|
+---------------------------------------+------------------------+
```
That would be awesome, cause then I can just scroll down the table and choose a fitting category for each bank comment. This table will then be used to create a key to categorize future expenses.

Thanks in advance!

**Comment by piever** [comment]
So basically the comment column is something that is there already (maybe your bank gives you or something) and you want to fill on the right based on your choice of category and then starting from the ones that are actually filled in, your program would compute a function to associate a label to a comment?

**Comment by yakir12** [comment]
(thanks for this tailor-made level attention!)
The bank comments are already there, so I have a vector of strings, each element in this vector is a bank comment (about 1000 elements). I also have a vector of categories (about 20 of them). I want to associate each bank comment to one of the categories. I'd like to choose a category for each of the comments. The value of the category can come from, as you say, previously chosen categories, or... from a set of possible categories.

**Comment by piever** [comment]
Now you can do (you need to be on master of InteractBase I believe):

```julia
using TableWidgets

comments = ["2018-06-10 ICA SUPERMARKET SODER", "2018-06-05 SKANETRAFIKEN, MALMO C"]

categories = ["Food", "Furniture", "Clothes"]
wdg = TableWidgets.financetable(comments, categories = categories)
display(wdg);
```

And `observe(wdg)` will be an observable that updates in real time with the modified table.

The available autocomplete options update automatically as soon as one option not in the list is added to the table, see [this demo](https://vimeo.com/281257363).

**Comment by yakir12** [comment]
WOW. Real nice. Thanks!!!
